# ----------- CONFIGURABLE START -----------
title:            "Prueba de Concepto"
description:      "Ejemplo de blog creado con el tema Scribble de Jekyll"
url:              "https://antoniohernan.github.io/pruebadeconcepto/" # Site url, without a slash at the end.
signoff:          "antoniohernan" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons
theme: jekyll-theme-minimal

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         Sobre mí
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink: pretty
defaults:
  - values:
      layout: "default"