site_name: Prueba de Concepto
site_url: https://pruebadeconcepto.es
repo_url: https://github.com/antoniohernan/pruebadeconcepto
site_description: "Un informático de siempre… en estos tiempos modernos"
nav:
    - Home: index.md
    - About: about.md
theme:
  name: material
  favicon: assets/images/favicon.ico
  font: false
copyright: Copyright &copy; 2019-2023 Antonio Hernan
