site_name: Prueba de Concepto
site_url: https://pruebadeconcepto.es
site_description: "Un informático de siempre… en estos tiempos modernos"

theme:
  name: material
  language: "en"
  logo: images/logo_white.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

# extra_css:
#  - stylesheets/extra.css

copyright: Copyright &copy; 2019-2023 Antonio Hernan

markdown_extensions:
  - attr_list
  - admonition
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences

plugins:
  - awesome-pages:
      strict: false
  - redirects
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_config: "hooks.on_config:deploy_hooks"
  - rss:
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d"
      pretty_print: !ENV [PRETTY_RSS, false]
      length: 30
      match_path: "Tech Blog/.*"

nav:
    - Inicio: index.md
    - Generales:
      - Hola mundo!!: gen/gen_hello-world.md
    - Informática Viejuna:
      - ¡Hola! Me llamo Guybrush Threepwood, ¡y quiero ser un pirata!: infov/infv_guybrush.md
      - ¿Y esto tiene discos SSD?: infov/infv_discossd.md
    - Tecnología:
      - Envía ficheros desde Github a EC2 con actions: tec/tec_actionsec2.md
    - RaspberryPi:
      - Introducción: rpi/rpi_intro.md
      - Instalación Básica I: rpi/rpi_install_i.md
      - Instalación Básica II: rpi/rpi_install_ii.md
      - Securización: rpi/rpi_securizacion.md
      - Copias de Seguridad: rpi/rpi_backup.md
      - Práctico 1 - Wordpress 1: rpi/rpi_wordpress1.md
      - Práctico 1 - Wordpress 2: rpi/rpi_wordpress2.md
      - Práctico 2 - Gestor de Descargas: rpi/rpi_downmanager.md
      - Práctico 3 - Servidor Impresión/AirPrint: rpi/rpi_airprint.md
      - Práctico 4 - Servidor Copias de Seguridad: rpi/rpi_backupserver.md
      - Práctico 5 - Domótica, Cámaras IP y RaZberry: rpi/rpi_domotica.md
      - Práctico 6 - Media Center: rpi/rpi_mediacenter.md
      - Práctico 7 - Emulación de juegos: rpi/rpi_emulador.md
      - Alternativas a RPi: rpi/rpi_alternativas.md
      - Apéndices (I) - Reinicio de router: rpi/rpi_apendice1.md
      - Apéndices (II) - XBMC con MariaDB para BBDD distribuida: rpi/rpi_apendice2.md
      - Apéndices (III) - Administración con Webmin: rpi/rpi_apendice3.md
    - Acerca de:
      - Acerca de mi y mis pruebas de concepto: about/about_acercademi.md
      - Política de privacidad: about/about_privacy-policy.md
