name: Sast Semgrep
on:
  workflow_dispatch:
jobs:
  sast_semgrep:
    permissions:                                                                         
      contents: read
    uses: ramshackle-code/sast_semgrep/.github/workflows/sast_semgrep.yml@c3e26900cb8ddde7881d857f0cebb1a7a694e1b7   #v1.0.1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
