name: Static application security testing
on:
#  push:
  workflow_dispatch:
jobs:
  sast_semgrep:
    permissions:                                                                         
      contents: read
    uses: ramshackle-code/sast_semgrep/.github/workflows/sast_semgrep.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
